### ISSUE TITLE
Src doesn't copy .icns file

### ISSUE THREAD

**Issue by kooliokey** [nwjs/grunt-nw-builder#129]
```
nodewebkit: {
	options: {
		version: 'v0.11.6',
		platforms: ['osx'],
		buildDir: '../build',
		// macIcns: '/AppIcon.icns',
		appName: undefined,
		// macZip: true
	},
	src: ['./**/*', './AppIcon.icns', '!./node_modules/grunt/**', '!./node_modules/grunt-*/**']
}
```

I am trying to use all files in the src directory (cwd of the Gruntfile) as the app's files and that includes the AppIcon.icns file. It wasn't being copied with the first blob in the src array, so I explicitly added it and it still didn't work. I'm thinking it may be something the builder is jumping over for some reason? I have tried it both zipped and not.

Any suggestions for a solution?
Thanks!

**Comment by felicienfrancois** [comment]
It probably works (the icns file is probably effectively copied in the destination folder) but don't changes the icon for the following reason(s):

1°) macIcns option does not copy the icns file at the same place than src files (`Contents/Resources/` vs `Contents/Resources/app.nw/`)
2°) the macIcns file is also renamed to `nw.icns` in order to replace the current icon

I can't see any reason not to use the macIcns option but if you really want to do so, you will have to change the "path of the icon file" (ie `CFBundleTypeIconFile` property) in the `Contents/info.plist` manifest to something like that: `app.nw/AppIcon.icns`

**Comment by kooliokey** [comment]
@felicienfrancois I'm sorry, I neglected to mention in my original post that I get an error if I uncomment the macIcns line in my original post, I get an error about the file not existing: `Fatal error: ENOENT, no such file or directory './AppIcon.icns'` That is what lead me to check if it was getting copied, because the file definitely exists in the same directory as my Gruntfile.js so I assumed it was looking in the app.nw folder. 

I do also get this error right after it is logged that it created the release folder osx64. Could it be looking in there? And how would I fix that?

Thanks!

**Comment by felicienfrancois** [comment]
Maybe you've missed a dot in the path ?
```javascript
macIcns: '/AppIcon.icns', // should be either './AppIcon.icns' or 'AppIcon.icns'
```

You can also check the case of the filename

**Comment by kooliokey** [comment]
I got the error to go away because apparently my file didn't have the extension on it even though I thought it did. I added the extension and it didn't throw an error, but it also didn't replace the icon. I'm going to investigate further and I'll report back if there is anything else to add.

Thanks for the help so far!

**Comment by adam-lynch** [comment]
We've made some fixes around this. So it could've been a problem there or on your side, but it should be ok now. Thanks.
