### ISSUE TITLE
issue with mac node-webkit 0.9.2 archive  downloaded from s3

### ISSUE THREAD

**Issue by cniaulin** [nwjs/grunt-nw-builder#79]
It seems that there is something wrong with the mac node-webkit 0.9.2 archive on s3.

Here are my logs when I try build a mac app:
Downloading: https://s3.amazonaws.com/node-webkit/v0.9.2/node-webkit-v0.9.2-osx-ia32.zip
Unzipping: /Users/Charles/Documents/git/aircall-client/buildStaging/cache/mac/0.9.2/node-webkit-v0.9.2-osx-ia32.zip
Fatal error: ZIP end of central directory record signature invalid (expects 0x06054b50, actually 0x6d783f3c)

**Comment by DogsForArms** [comment]
Hi.  I had cnialin's problem where it is trying to pull from s3 when I use 'grunt nodewkbuild' on a project.  I updated with 
' npm install grunt-node-webkit-builder --save-dev '
and tried again, but this time instead of pulling from s3 it is trying to grab from dl.node-webkit.org
Here is the output after 'grunt nodewkbuild'


Running "nodewebkit:src" (nodewebkit) task
Using v0.9.2
Create cache folder in /Users/ethan/Desktop/popcorn-app-master/cache/0.9.2
Downloading: http://dl.node-webkit.org/v0.9.2/node-webkit-v0.9.2-osx-ia32.zip
Create cache folder in /Users/ethan/Desktop/popcorn-app-master/cache/0.9.2
Downloading: http://dl.node-webkit.org/v0.9.2/node-webkit-v0.9.2-osx-x64.zip
  downloading [--------------------] 0% 70.0sERROR: The version 0.9.2 does not have a corresponding build posted at http://dl.node-webkit.org/. Please choose a version from that list.


Indeed this is the case when I visit http://dl.node-webkit.org/v0.9.2  I see that there are no such node-webkit-v0.9.2-osx-x64.zip at http://dl.node-webkit.org/v0.9.2

I have tried changing the version of nodewk in this project by modifying the gruntfile, to a version which would have the corresponding 64 and 32 bit mac environments.  But I'm not sure what this does to the project.  It seems to crash at runtime.  I am trying to build popcorn-time (https://github.com/popcorn-time/popcorn-app/blob/master/README.md)

I am not sure what to do.  Help would b greatly appreciated!  Thanks.
